services:
  - type: web
    name: chillguys-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CG.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CG.settings
    buildFilter:
      paths:
        - CG/
    repo:
      rootDir: CG
