# Generated by Django 5.1.7 on 2025-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualityindex',
            name='wqi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
